
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Limbo
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    int opcion;
    Polinomio polinomio1;
    Polinomio polinomio2;
    boolean banderaGlobal;
    DefaultListModel model;
    
    public FramePrincipal() {
        initComponents();
        polinomio1 = new Polinomio();
        polinomio2 = new Polinomio();
        banderaGlobal = false;
        model = new DefaultListModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jSplitPane1 = new javax.swing.JSplitPane();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnSignoSuma = new javax.swing.JButton();
        btnSignoMenos = new javax.swing.JButton();
        btnResolver = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSignoMenos1 = new javax.swing.JButton();
        btnSimplificar = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listHistorial = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        txtResultado = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnSumar.setText("Sumar");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });

        btnMultiplicar.setText("Multiplicar");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });

        btnRestar.setText("Restar");
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });

        btnDividir.setText("Dividir");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });

        btn1.setForeground(new java.awt.Color(51, 51, 51));
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btnSignoSuma.setText("+");
        btnSignoSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignoSumaActionPerformed(evt);
            }
        });

        btnSignoMenos.setText("-");
        btnSignoMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignoMenosActionPerformed(evt);
            }
        });

        btnResolver.setText("Resolver");
        btnResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolverActionPerformed(evt);
            }
        });

        btnX.setText("X");
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        btnEliminar.setText("<-");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSignoMenos1.setText("^");
        btnSignoMenos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignoMenos1ActionPerformed(evt);
            }
        });

        btnSimplificar.setText("Simplificar");
        btnSimplificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimplificarActionPerformed(evt);
            }
        });

        btnTotal.setText("=");
        btnTotal.setEnabled(false);
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSumar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRestar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMultiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSignoSuma, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(btn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSignoMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnResolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSignoMenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSimplificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnX, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignoSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignoMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignoMenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimplificar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane2.setViewportView(listHistorial);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtResultado.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtResultado)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>                        

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        String polinomioTxt = txtResultado.getText();
        polinomioTxt = polinomioTxt + "1";
        
        txtResultado.setText(polinomioTxt);
    }                                    

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        String polinomioTxt = txtResultado.getText();
        polinomioTxt = polinomioTxt + "2";
        
        txtResultado.setText(polinomioTxt);
    }                                    

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        String polinomioTxt = txtResultado.getText();
        polinomioTxt = polinomioTxt + "3";
        
        txtResultado.setText(polinomioTxt);
    }                                    

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        String polinomioTxt = txtResultado.getText();
        polinomioTxt = polinomioTxt + "4";
        
        txtResultado.setText(polinomioTxt);
    }                                    

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        String polinomioTxt = txtResultado.getText();
        polinomioTxt = polinomioTxt + "5";
        
        txtResultado.setText(polinomioTxt);
    }                                    

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        String polinomioTxt = txtResultado.getText();
        polinomioTxt = polinomioTxt + "6";
        
        txtResultado.setText(polinomioTxt);
    }                                    

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        String polinomioTxt = txtResultado.getText();
        polinomioTxt = polinomioTxt + "7";
        
        txtResultado.setText(polinomioTxt);
    }                                    

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        String polinomioTxt = txtResultado.getText();
        polinomioTxt = polinomioTxt + "8";
        
        txtResultado.setText(polinomioTxt);
    }                                    

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        String polinomioTxt = txtResultado.getText();
        polinomioTxt = polinomioTxt + "9";
        
        txtResultado.setText(polinomioTxt);
    }                                    

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        String polinomioTxt = txtResultado.getText();
        polinomioTxt = polinomioTxt + "0";
        
        txtResultado.setText(polinomioTxt);
    }                                    

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String polinomioTxt = txtResultado.getText();
        polinomioTxt = polinomioTxt + ".";
        
        txtResultado.setText(polinomioTxt);
    }                                        

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        String polinomioTxt = txtResultado.getText();
        if(polinomioTxt.length() > 0){
            polinomioTxt = polinomioTxt.substring(0,polinomioTxt.length()-1);
            txtResultado.setText(polinomioTxt);
        }
    }                                           

    private void btnSignoSumaActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        String polinomioTxt = txtResultado.getText();
        polinomioTxt = polinomioTxt + "+";
        
        txtResultado.setText(polinomioTxt);
    }                                            

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        String polinomioTxt = txtResultado.getText();
        polinomioTxt = polinomioTxt + "x";
        
        txtResultado.setText(polinomioTxt);
    }                                    

    private void btnSignoMenosActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        String polinomioTxt = txtResultado.getText();
        polinomioTxt = polinomioTxt + "-";
        
        txtResultado.setText(polinomioTxt);
    }                                             

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if(!banderaGlobal){
            if(isPolinomio() && !txtResultado.getText().equals("")){
                convertirAPolinomio(txtResultado.getText(), polinomio1);
                txtResultado.setText("");
                model.addElement(polinomio1.toString() + " + ");
                listHistorial.setModel(model);
                banderaGlobal = !banderaGlobal;
                opcion = 1;
                deshabilitarBotones();
            } else{
                JOptionPane.showMessageDialog(null, "Existe algún problema con la sintaxis de su polinomio, lo siento");
            }
        }
    }                                        

    private void btnSignoMenos1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        String polinomioTxt = txtResultado.getText();
        polinomioTxt = polinomioTxt + "^";
        
        txtResultado.setText(polinomioTxt);
    }                                              

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if(!banderaGlobal){
            if(isPolinomio() && !txtResultado.getText().equals("")){
                convertirAPolinomio(txtResultado.getText(), polinomio1);
                txtResultado.setText("");
                model.addElement(polinomio1.toString() + " - ");
                listHistorial.setModel(model);
                banderaGlobal = !banderaGlobal;
                opcion = 2;
                deshabilitarBotones();
            } else{
                JOptionPane.showMessageDialog(null, "Existe algún problema con la sintaxis de su polinomio, lo siento");
            }
        }
    }                                         

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        if(!banderaGlobal){
            if(isPolinomio() && !txtResultado.getText().equals("")){
                convertirAPolinomio(txtResultado.getText(), polinomio1);
                txtResultado.setText("");
                model.addElement(polinomio1.toString() + " * ");
                listHistorial.setModel(model);
                banderaGlobal = !banderaGlobal;
                opcion = 3;
                deshabilitarBotones();
            } else{
                JOptionPane.showMessageDialog(null, "Existe algún problema con la sintaxis de su polinomio, lo siento");
            }
        }
    }                                              

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        if(!banderaGlobal){
            if(isPolinomio() && !txtResultado.getText().equals("")){
                convertirAPolinomio(txtResultado.getText(), polinomio1);
                txtResultado.setText("");
                model.addElement(polinomio1.toString() + " / ");
                listHistorial.setModel(model);
                banderaGlobal = !banderaGlobal;
                opcion = 4;
                deshabilitarBotones();
            } else{
                JOptionPane.showMessageDialog(null, "Existe algún problema con la sintaxis de su polinomio, lo siento");
            }
        }
    }                                          

    private void btnResolverActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        if(isPolinomio() && !txtResultado.getText().equals("")){
            convertirAPolinomio(txtResultado.getText(), polinomio1);
            Lista resultados = polinomio1.resolver();
            Nodo aux = resultados.getInicio();
            model.addElement(polinomio1.toString() + " resultados: ");
            int contador = 0;
            while(aux != null){
                contador++;
                model.addElement("respuesta numero " + contador + ": " + aux.getDato()); 
                aux = aux.getSiguiente();
            }
            listHistorial.setModel(model);
            polinomio1.setInicio(null);
            txtResultado.setText("");
        } else{
            JOptionPane.showMessageDialog(null, "Existe algún problema con la sintaxis de su polinomio, lo siento");
        }
    }                                           

    private void btnSimplificarActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        if(isPolinomio() && !txtResultado.getText().equals("")){
            convertirAPolinomio(txtResultado.getText(), polinomio1);
            model.addElement(polinomio1.toString());
            polinomio1.simplificar();
            model.addElement("polinomio simplificado: " + polinomio1.toString());
            listHistorial.setModel(model);
            polinomio1.setInicio(null);
        } else{
            JOptionPane.showMessageDialog(null, "Existe algún problema con la sintaxis de su polinomio, lo siento");
        }
    }                                              

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        DefaultListModel listModel = (DefaultListModel) listHistorial.getModel();
        listModel.removeAllElements();
        txtResultado.setText("");
    }                                          

    public void deshabilitarBotones(){
        btnDividir.setEnabled(false);
        btnMultiplicar.setEnabled(false);
        btnRestar.setEnabled(false);
        btnSumar.setEnabled(false);
        btnResolver.setEnabled(false);
        btnSimplificar.setEnabled(false);
        
        btnTotal.setEnabled(true);
    }
    
    public void habilitarBotones(){
        btnDividir.setEnabled(true);
        btnMultiplicar.setEnabled(true);
        btnRestar.setEnabled(true);
        btnSumar.setEnabled(true);
        btnResolver.setEnabled(true);
        btnSimplificar.setEnabled(true);
        
        btnTotal.setEnabled(false);
    }
    
    
    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        switch (opcion) {
            case 1:
                if(isPolinomio() && !txtResultado.getText().equals("")){
                    Polinomio polinomioAuxiliar = new Polinomio();
                    convertirAPolinomio(txtResultado.getText(), polinomio2);
                    txtResultado.setText("");
                    polinomioAuxiliar = polinomio1.sumar(polinomio2);
                    txtResultado.setText("");
                    model.addElement(polinomio2.toString());
                    model.addElement("resultado = " + polinomioAuxiliar.toString());
                    listHistorial.setModel(model);
                    polinomio1.setInicio(null);
                    polinomio2.setInicio(null);
                    banderaGlobal = !banderaGlobal;
                    habilitarBotones();
                } else{
                    JOptionPane.showMessageDialog(null, "Existe algún problema con la sintaxis de su polinomio, lo siento");
                }   break;
            case 2:
                if(isPolinomio() && !txtResultado.getText().equals("")){
                    Polinomio polinomioAuxiliar = new Polinomio();
                    convertirAPolinomio(txtResultado.getText(), polinomio2);
                    txtResultado.setText("");
                    polinomioAuxiliar = polinomio1.restar(polinomio2);
                    txtResultado.setText("");
                    model.addElement(polinomio2.toString());
                    model.addElement("resultado = " + polinomioAuxiliar.toString());
                    listHistorial.setModel(model);
                    polinomio1.setInicio(null);
                    polinomio2.setInicio(null);
                    banderaGlobal = !banderaGlobal;
                    habilitarBotones();
                } else{
                    JOptionPane.showMessageDialog(null, "Existe algún problema con la sintaxis de su polinomio, lo siento");
                }   break;
            case 3:
                if(isPolinomio() && !txtResultado.getText().equals("")){
                    Polinomio polinomioAuxiliar = new Polinomio();
                    convertirAPolinomio(txtResultado.getText(), polinomio2);
                    txtResultado.setText("");
                    polinomioAuxiliar = polinomio1.multiplicar(polinomio2);
                    txtResultado.setText("");
                    model.addElement(polinomio2.toString());
                    model.addElement("resultado = " + polinomioAuxiliar.toString());
                    listHistorial.setModel(model);
                    polinomio1.setInicio(null);
                    polinomio2.setInicio(null);
                    banderaGlobal = !banderaGlobal;
                } else{
                    JOptionPane.showMessageDialog(null, "Existe algún problema con la sintaxis de su polinomio, lo siento");
                }   break;
            case 4:
                if(isPolinomio() && !txtResultado.getText().equals("")){
                    ArrayList<Polinomio> polinomioAuxiliar = new ArrayList<Polinomio>();
                    convertirAPolinomio(txtResultado.getText(), polinomio2);
                    txtResultado.setText("");
                    polinomioAuxiliar = polinomio1.dividir(polinomio2);
                    txtResultado.setText("");
                    model.addElement(polinomio2.toString());
                    model.addElement("cociente = " + polinomioAuxiliar.get(0).toString());
                    model.addElement("residuo = " + polinomioAuxiliar.get(1).toString());
                    listHistorial.setModel(model);
                    polinomio1.setInicio(null);
                    polinomio2.setInicio(null);
                    banderaGlobal = !banderaGlobal;
                    habilitarBotones();
                } else{
                    JOptionPane.showMessageDialog(null, "Existe algún problema con la sintaxis de su polinomio, lo siento");
                }   break;
            default:
                break;
        }
    }                                        

    public void convertirAPolinomio(String polinomio, Polinomio polinomioAux){
        polinomioAux.setInicio(null);
        String[] monomios = txtResultado.getText().split("(?=[+-]?[-+]+)");
        int cantidad = monomios.length;
        int i = 0;
        while (i < cantidad) {
            //JOptionPane.showMessageDialog(null, monomios[i]);
            if(monomios[i].contains("x")){
                String[] valores = monomios[i].split("x");
                
                switch (valores.length) {
                    case 1:
                        if(valores[0].equals("-")){
                            //forma -x
                            polinomioAux.insertarI(-1.0, 1);
                        } else if (valores[0].equals("+")){
                            //forma +x
                            polinomioAux.insertarI(1.0, 1);
                        } else {
                            //forma ax
                            if(valores[0].contains("-")){
                                polinomioAux.insertarI(Double.parseDouble(valores[0]) , 1);
                            } else if(valores[0].contains("+")) {
                                //forma +ax
                                valores[0] = valores[0].replace("+", "");
                                polinomioAux.insertarI(Double.parseDouble(valores[0]), 1);
                            } else {
                                //forma ax
                                polinomioAux.insertarI(Double.parseDouble(valores[0]), 1);
                            }
                            
                        }   break;
                    case 0:
                        //forma x
                        polinomioAux.insertarI(1.0, 1);
                        break;
                    default:
                        valores[1] = valores[1].replace("^", "");
                        if(valores[0].equals("")){
                            //forma de x^b
                            polinomioAux.insertarI(1.0, Integer.parseInt(valores[1]));
                        }else {
                            if(valores[0].equals("-")){
                                //forma -x^b
                                polinomioAux.insertarI(-1.0, Integer.parseInt(valores[1]));
                            } else {
                                //forma ax^b
                                if(valores[0].equals("+")){
                                    //forma +x^b
                                    polinomioAux.insertarI(1.0, Integer.parseInt(valores[1]));
                                } else {
                                    //forma +ax^b
                                    polinomioAux.insertarI(Double.parseDouble(valores[0]), Integer.parseInt(valores[1]));
                                }
                            }
                        }
                        break;
                }
            } else {
                // forma +-a
                polinomioAux.insertarI(Double.parseDouble(monomios[i]), 0);
            }
            i++;
        }
    }
    
    public boolean isPolinomio(){
        boolean bandera = true;
        String[] monomios = txtResultado.getText().split("(?=[+-]?[-+]+)");
        int cantidad = monomios.length;
        int i = 0;
        while (i < cantidad &&  bandera) {
            //JOptionPane.showMessageDialog(null, monomios[i]);
            if(!monomios[i].matches("(\\+?|-)([0-9]+(\\.[0-9])?)?(x(\\^?[1-9]+)?)?")){
                bandera = !bandera;
            } 
            i++;
        }
        return bandera;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify                     
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnResolver;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSignoMenos;
    private javax.swing.JButton btnSignoMenos1;
    private javax.swing.JButton btnSignoSuma;
    private javax.swing.JButton btnSimplificar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JButton btnTotal;
    private javax.swing.JButton btnX;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JList<String> listHistorial;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration                   
}
